services:
  simulation:
    container_name: drone0
    build: ../../containerization
    stdin_open: true
    tty: true
    volumes:
#      - \\wsl.localhost\Ubuntu\mnt\wslg:/tmp
      - ./mnt:/usr/drone0/:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: /bin/bash -c "./entrypoint.sh"
