version: "3.8"
volumes:
  vehicle:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
services:
  simulation:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: sim
    build: .
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1234:1234"
    volumes:
      - vehicle:/usr/local/vehicle
#      - \\wsl.localhost\Ubuntu\mnt\wslg:/tmp
    command: "/bin/bash -c
              'if [ -z \"$$WORLD\" ]; then export WORLD=\"$env:WORLD\"; fi;
               if [ -z \"$$PARAM\" ]; then export PARAM=\"$env:PARAM\"; fi;
               if [ \"$$WORLD\" == \":WORLD\" ]; then export WORLD=\"$WORLD\"; fi;
               if [ \"$$PARAM\" == \":PARAM\" ]; then export PARAM=\"$PARAM\"; fi;
               ./vehicle/scripts/sim-start.sh'"