version: "3.8"
volumes:
  vehicle:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
services:
  simulation:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: sim
    build:
      context: .
      args:
        - VEHICLE=copter
        - BOARD=sitl
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1234:1234"
    volumes:
      - vehicle:/usr/local/vehicle
      - \\wsl.localhost\Ubuntu\mnt\wslg:/tmp
    # Starting directory is ~/
#    command:
#      - "./vehicle/sim.sh"