version: "3.8"
volumes:
  vehicle:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind
  display:
    driver: local
    driver_opts:
      type: none
      device: \\wsl.localhost\Ubuntu\mnt\wslg
      o: bind
services:
  simulation:
    container_name: sim
    build: .
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - vehicle:/usr/local/vehicle
      - display:/tmp
# TODO: specify script to run on boot?
#    command:
#      - "/home/vehicle/src/start.sh"