networks:
  lens-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
services:
  drone:
    deploy:
      mode: replicated
      replicas: 2
    build: .
    networks:
      - lens-net
    stdin_open: true
    tty: true
    command: "/bin/bash"
